### ISSUE TITLE
Dynamical creation of variables

### ISSUE THREAD

**Issue by heiderich** [JuliaAlgebra/MultivariatePolynomials.jl#100]
I'd like to create multivariate polynomials in variables whose names I cannot hardcode. I rather want to create the variables using an array of strings or symbols. Is this possible?

As `@polyvar` is a macro, its arguments are not evaluates. So something like

```julia
using DynamicPolynomials
v = "x"
@polyvar v
```

defines a variable `v` and not `x`.

I would appreciate a function taking an array or strings of symbols as an input and returns an array of variables. Does this exist?

**Comment by saschatimme** [comment]
There are two possibilities.
1) Assuming you have already some polynomial, term or variable `x` then you can call [`similarvariable(x, :y)`](https://juliaalgebra.github.io/MultivariatePolynomials.jl/stable/types.html#MultivariatePolynomials.similarvariable) to create a variable with name `y`.

2) You can directly use the `PolyVar` constructor of DynamicPolynomials
```julia

julia> using DynamicPolynomials

julia> vars = PolyVar{true}.(["a", "b", "c"])
3-element Array{PolyVar{true},1}:
 a
 b
 c

julia> vars
3-element Array{PolyVar{true},1}:
 a
 b
 c
```

**Comment by heiderich** [comment]
Thank you. The `PolyVar` constructor is what I was looking for. I think it deserves more publicity. ;-)
