### ISSUE TITLE
Subs is a no op for arrays

### ISSUE THREAD

**Issue by saschatimme** [JuliaAlgebra/MultivariatePolynomials.jl#103]
Something I tripped over already a couple of times:
```julia
julia> using DynamicPolynomials

julia> @polyvar x y
(x, y)

julia> f = [x+y, y+1]
2-element Array{Polynomial{true,Int64},1}:
 x + y
 y + 1

julia> subs(f, y => x)
2-element Array{Polynomial{true,Int64},1}:
 x + y
 y + 1
```

`subs` should either just apply the substitution element wise or error. But this is really annoying.

**Comment by blegat** [comment]
Indeed, since `f` is not an `AbstractPolynomialLike`, it assumes that it is a constant hence there is not variable:
https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/fd3c42e5341d183d5ec49b4a69ebdb708ac2b7eb/src/substitution.jl#L79

I agree that this is an issue
