### ISSUE TITLE
Detect which varriable a polynomial contains

### ISSUE THREAD

**Issue by TorkelE** [JuliaAlgebra/MultivariatePolynomials.jl#109]
Given this code:
```julia
@polyvar a b c d
p = a^2+2b*c-1
```
It would be useful to (either or both) have something like
```julia
in(a,p)        #returns true
vars(p)        #returns (a,b,c)
```
allowing the user to detect which variables a polynomial contains.
(this might already be possible, then this is rather a question of how, and possible a suggestion to update the docs)

**Comment by saschatimme** [comment]
There's [`variables`](https://juliaalgebra.github.io/MultivariatePolynomials.jl/stable/types.html#MultivariatePolynomials.variables):
```julia

julia> using DynamicPolynomials

julia> @polyvar a b c d
(a, b, c, d)

julia> p = a^2+2b*c-1
a² + 2bc - 1

julia> variables(p)
3-element Array{PolyVar{true},1}:
 a
 b
 c

julia> a in variables(p)
true
```

But I agree that it is quite hidden in the documentation.

**Comment by TorkelE** [comment]
That's a great help, Thanks!
