### ISSUE TITLE
Imported functions cannot see polyvars

### ISSUE THREAD

**Issue by TorkelE** [JuliaAlgebra/MultivariatePolynomials.jl#110]
I have been having some weird issues, which I only vaguely understand. I think I have managed to create a minimal example though.

The problem appears when I have written functions to manipulate polynomials and put them in an external module. When I then import this module these functions cannot properly detect polyvars.

This is my base code:
```julia
using DynamicPolynomials

module test_module
using DynamicPolynomials
using InteractiveUtils
function change_poly_1(pol)
    subs.(pol, Ref(x => [1,2,3,4,5]))
end
function change_poly_2(pol)
    @polyvar x[1:5]
    subs.(pol, Ref(x => [1,2,3,4,5]))
end
function change_poly_3(pol)
    println(varinfo())
    subs.(pol, Ref(x => [1,2,3,4,5]))
end
export change_poly_1, change_poly_2, change_poly_3
end

@polyvar x[1:5]
pol = x[1]*x[2]+2x[3]-5
using Main.test_module

function change_poly_internal(pol)
    subs.(pol, Ref(x => [1,2,3,4,5]))
end
```
This fetches `DynamicPolynomials` for use, declares the module `test_module`, which contains three functions for substituting variables in polynomials. Finally I create a polynomial, imports the module, and creates another function for making substitutions in polynomials.

Calling the non-module function works fine:
```julia 
change_poly_internal(pol)
```
(This returns 3)

Calling the first (most basic) function from the module gives us the main problem
```julia
change_poly_1(pol)
```
this yields the error `UndefVarError: x not defined`. The function thinks the polyvar is not defined. 
(my problem is to make this type of function able to do the required substitution)

The following two functions should give some additional information.
```julia
change_poly_2(pol)
```
This works, however it does not make any actual change to the polynomial (the identically named polyvars I declare inside the function is seen as different from the ones inside the polynomial, by the substitution method).

Finally 
```julia
change_poly_3(pol)
```
fails like the first one, but also lists all the variables, including an entry `| x                |   220 bytes | 5-element Array{PolyVar{true},1} |`, which should be the one I am looking for. Anyone with a better understanding of polyvars who can tell what is going on. Is what I am trying to do even possible?

**Comment by blegat** [comment]
`change_poly_2` would work with [TypedPolynomials](https://github.com/JuliaAlgebra/TypedPolynomials.jl) because it compares variables by names.
In [DynamicPolynomials](https://github.com/JuliaAlgebra/DynamicPolynomials.jl), variables are compared by id hence calling `@polyvar` with the same name will yield different variables.

`change_poly_1` and `change_poly_3` are not expected to work. `@polyvar` creates a local vector `x`, containing the 5 variables created but this variable is only local hence it cannot be accessed from another module. You need to pass this variable as function argument is you want to use it.

**Comment by TorkelE** [comment]
Thanks, I think I understand.

**Comment by saschatimme** [comment]
Alternatively you can also just query the variables
```julia
function change_poly_3(pol)
    println(varinfo())
    subs.(pol, Ref(variables(pol) => [1,2,3,4,5]))
end
```

Also if you actual want to evaluate a polynomial you can use the syntax
```julia
vars = variables(pol)
map(p -> p(vars => [1,2,3,4,5]), pol)
```

**Comment by TorkelE** [comment]
That's interesting!

Now say that I instead of one set of variables, I have two set of variables. One is a set of normal variables, while the other is actually some parameters. I want to use the substitution method to fix the parameter variables, but not the normal ones (@saschatimme probably starts to recognise this...).

So now we have the system
```julia
@polyvar x[1:2]
@polyvar p[1:2]
pol = p[1]*x[1] + p[2]*x[2]-5
```
I can still change the variables internally with ease by using
```julia
function change_poly_internal(pol)
    subs.(pol, Ref(p => [1,2]))
end
change_poly_internal(pol)
```

I think I have managed using this generally and from a module. However, it requires this quite convoluted function:
```julia
using DynamicPolynomials
@polyvar x[1:2]
@polyvar p[1:2]
pol = p[1]*x[1] + p[2]*x[2]-5

module my_module
using DynamicPolynomials
function change_poly(pol)
    swap_values = [1.,2.]
    vars = variables(pol)
    vars_to_swap = Vector{PolyVar{true}}()
    for var in vars
        for i = 1:length(swap_values)
            if var.name == string("p[",i,"]")
                push!(vars_to_swap,var)
            end
        end
    end
    subs.(pol, Ref(vars_to_swap => swap_values))
end
export change_poly
end

using Main.my_module
change_poly(pol)
```
This seems to work for doing the replacement selectively though.

**Comment by saschatimme** [comment]
I think the easiest way is to explicitly pass around the set of parameters.

For example you can define

```julia
function variables(polys; parameters=nothing)
    variables = MP.variables(polys)
    if parameters !== nothing
        setdiff!(variables, parameters)
    end
   variables
end
```
to give you all variables of a system (ignoring the parameters).

**Comment by TorkelE** [comment]
Yes. Thanks, I think I have plenty of ideas on how to solve my problems now.
