### ISSUE TITLE
Adjoint of polynomials and complex numbers

### ISSUE THREAD

**Issue by ahumenberger** [JuliaAlgebra/MultivariatePolynomials.jl#116]
It seems that the implementation of adjoint is neglecting the fact that the unknowns of polynomials can be replaced by complex numbers.
https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/fe0d7ca124f9dedcb577c242c8108dee0cb16858/src/operators.jl#L116

```julia
using DynamicPolynomials
@polyvar x
p = (2-im)*x
adj_p = adjoint(p)
adj_p(x => 2+im)
```
The above piece of code yields `3+4im` but the result should actually be `5`.

**Comment by saschatimme** [comment]
Conjugation is not an algebraic operation, so there is a priori no conjugation of variables. 
For me the adjoint is a map between polynomial rings, acting only on the coefficients of the polynomial.
Therefore, I think the result is correct here.

**Comment by ahumenberger** [comment]
Okay, I see your point. So the difference lies in viewing the polynomial as an element in the polynomial ring or as a function?

**Comment by chriscoey** [comment]
Coincidentally, I experienced this point of confusion yesterday when taking to Sascha. I think of them as functions too and I was hoping to add complex polynomial extensions to multivariatepolynomials and sumofsquares to enable modeling and solving complex sum-of-squares optimization problems (which involve real-valued/Hermitian complex polynomial functions). I will try to discuss with @blegat and @saschatimme in the next couple days.

How do you intend to use conjugation?

**Comment by ahumenberger** [comment]
I'm not using it directly, I came across it while facing JuliaAlgebra/DynamicPolynomials.jl#49.
In the end, it does not matter for me as I'm not working with complex numbers but rationals. I was just curios/confused about the implementation of adjoint.

**Comment by saschatimme** [comment]
> Okay, I see your point. So the difference lies in viewing the polynomial as an element in the polynomial ring or as a function?
Yes exactly :)
