### ISSUE TITLE
Deprecation of DataStructures.front

### ISSUE THREAD

**Issue by fgerick** [JuliaAlgebra/MultivariatePolynomials.jl#129]
I also found a deprecation error (sorry, can't find a simple reproduction) in 
https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/02c68c67d91aff97e55eaaa977eb73389cc6b50a/src/operators.jl#L108

should be replaced by 
```julia
t = DataStructures.first(buffer) 
```

**Comment by blegat** [comment]
Thanks for reporting the two issues !
