### ISSUE TITLE
Monomial printing bug

### ISSUE THREAD

**Issue by ahumenberger** [JuliaAlgebra/MultivariatePolynomials.jl#136]
There is a superfluous && at the end of the following line:

https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/905ee7c6e166fc955c2d4c4a912c06c1552bf421/src/show.jl#L58

**Comment by blegat** [comment]
Thanks for reporting it. It's weird that no error was thrown and tests are passing. I have reported the issue in https://github.com/JuliaLang/julia/issues/35549
