### ISSUE TITLE
unified interface for constructing variables

### ISSUE THREAD

**Issue by nsajko** [JuliaAlgebra/MultivariatePolynomials.jl#278]
`TypedPolynomials.@polyvar x` returns a single value, but `DynamicPolynomials.@polyvar x` returns a length-one tuple: 

```julia
julia> import TypedPolynomials, DynamicPolynomials

julia> TypedPolynomials.@polyvar a
a

julia> DynamicPolynomials.@polyvar b
(b,)
```

To get around this inconsistency, I currently do `@polyvar x dummy`, which is awkward.

Is there a better way?

**Comment by blegat** [comment]
We have https://juliaalgebra.github.io/MultivariatePolynomials.jl/dev/types/#MultivariatePolynomials.similar_variable to programatically create a new variable

**Comment by nsajko** [comment]
But to use `similar_variable` I first need a polynomial value, and I thought I need a variable to construct a polynomial value? Seems like a chicken and egg problem?

**Comment by blegat** [comment]
Note sure what your use case is. Can't you use `mod.@polyvar a` and then use `a` and not care about the returned type ?

**Comment by nsajko** [comment]
Ah, you're right about that, I don't have to care about which type `@polyvar` returns, given that it also defines a variable with the same name.
