### ISSUE TITLE
Unicode pretty printing

### ISSUE THREAD

**Issue by saschatimme** [JuliaAlgebra/MultivariatePolynomials.jl#52]
I wondered whether you would accept a PR where the default printing would use unicode magic to print sub- and superscripts:
```julia
julia> x^2-3x+4y^4
4y⁴ + x² - 3x
julia> x[1]^2-x[2]*x[3]^3
-x₂x₃³+x₁²
```

I have a working implementation for [FixedPolynomials](https://github.com/saschatimme/FixedPolynomials.jl/blob/master/src/show.jl#L57-L118). The heuristic for the subscripts is `match(r"([a-zA-Z]+)(?:_*)(\d+)", var)`, i.e. literals followed by an digit with an optional `_` in between.

**Comment by blegat** [comment]
Yes, that would improve readability significantly ! I wonder if there is a way to detect if the `io::IO` supports unicode.

**Comment by saschatimme** [comment]
I didn't found a way to detect unicode support (at least in 10 minutes).
But I think we should keep the current implementation under a new name anyway, since this it is easier to parse than the unicode. This could occur if someone wants so store a polynomial in a text file and parse it again at a later point.

**Comment by blegat** [comment]
We could probably do different things as a function of the MIME, e.g.
```
show(::IO, x^2-3x+4y^4*x)
4y^4*x + x^2 - 3x # parseable by Julia
show(::IO, ::MIME"text/plain", x^2-3x+4y^4*x)
4y⁴x + x² - 3x # Most readable
show(::IO, ::MIME"text/latex", x^2-3x+4y^4)
4y^4x + x^2 - 3x # parseable by LaTeX
```

**Comment by saschatimme** [comment]
Didn't knew about "text/latex"! Probably we should print there for `x[1:2]` `x_1` and `x_2` or what do you think?

**Comment by blegat** [comment]
Yes, we can do `x[1]` for the first one, `x₁` for `text/plain` and `x_1` for LaTeX.
