### ISSUE TITLE
Algebra organization

### ISSUE THREAD

**Issue by blegat** [JuliaAlgebra/MultivariatePolynomials.jl#53]
There are a few packages around the same topic: MultivariatePolynomials, [DynamicPolynomials](https://github.com/blegat/DynamicPolynomials.jl), [TypedPolynomials](https://github.com/rdeits/TypedPolynomials.jl), [MultivariateMoments](https://github.com/blegat/MultivariateMoments.jl), [SemialgebraicSets](https://github.com/blegat/SemialgebraicSets.jl), [Homotopy](https://github.com/JuliaHomotopyContinuation/Homotopy.jl), [HomotopyContinuation](https://github.com/JuliaHomotopyContinuation/HomotopyContinuation.jl), [FixedPolySystem](https://github.com/saschatimme/FixedPolySystem.jl)

What do you think of creating an organization like JuliAlgebra or JuliaAlgebra ?
@saschatimme I see you have created JuliaHomotopyContinuation, if you want to keep a separate organization, that is fine of course ;)

cc @saschatimme @rdeits  @joehuchette

**Comment by saschatimme** [comment]
I think `Homotopy` and `HomotopyContinuation` will live for now in the separate organization, but I would be happy to bring [FixedPolynomials](https://github.com/saschatimme/FixedPolynomials.jl)  under an organization. (`FixedPolySystem` will soon vanish.) 
I would prefer `JuliaAlgebra` as an organization name, word plays usually lose their appeal quite fast :D

**Comment by rdeits** [comment]
Yeah, that sounds great! And I agree that the "JuliAlgebra" wordplay is a bit too cute, so I'd vote for JuliaAlgebra.

**Comment by saschatimme** [comment]
Does anybody know how `METADATA.jl` handles package transfers?

**Comment by blegat** [comment]
I think you just need to make a PR updating the content of the [url file](https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/MultivariatePolynomials/url)

**Comment by blegat** [comment]
What should be the description of the organization we put on Github and the ecosystem page ?
"Algebraic Geometry", "Multivariate Polynomials", "Algebraic Computation", "Computational Algebra" ?

**Comment by saschatimme** [comment]
Good question. It's definitive not proper Algebraic Geometry, but Computational Algebra without anything like computing ideals etc. is also a little bit strange. Maybe "Numerical Algebra"?

**Comment by blegat** [comment]
I like "Numerical Algebra", is is close to "Numerical Linear Algebra" though so it might be confusing

**Comment by blegat** [comment]
In [Nemo.jl](https://github.com/wbhart/Nemo.jl) the use the terminology "Computer Algebra". What do you think of it ?
