### ISSUE TITLE
Determinant 

### ISSUE THREAD

**Issue by PBrdng** [JuliaAlgebra/MultivariatePolynomials.jl#58]
Hi,

it would be nice to call det(A) on a matrix A with DynamicPolynomials as entries. Is this easily implementable?

**Comment by blegat** [comment]
I just checked if it works:
```julia
julia> det([x^2 x+1; x-1 2])
ERROR: MethodError: no method matching inv(::MultivariatePolynomials.RationalPoly{DynamicPolynomials.Polynomial{true,Int64},DynamicPolynomials.Polynomial{true,Int64}})
```
the first step seems to be defining `Base.inv` for `RationalPoly` which seems easy to implement. PR welcome :)

**Comment by saschatimme** [comment]
I looked into at some previous point. I think one problem is that there is no general gcd implemented, so the `RationalPoly`s will grow significantly.
For small determinants (n < 4 or 5) one can implement Laplace's expansion since it doesn't need any division.

**Comment by blegat** [comment]
Yes gcd is not implemnted yet.
However we have got `divrem` implemented in [division.jl](https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/master/src/division.jl) so implementing Euclide's algorithm to compute the GCD shouldn't be to hard.

**Comment by saschatimme** [comment]
On a related note I just tried to combine [Nemo.jl](https://github.com/wbhart/Nemo.jl) with the `subs` method:
```julia
Rx, x = PolynomialRing(ComplexField(64), "x")
Ry, y = PolynomialRing(ComplexField(64), "y")

@polyvar a b
f = a^2+2ab+1
subs(f, a => x, b => y)
```
but I just get
```
ERROR: MethodError: no method matching one(::Type{Any})

Stacktrace:
 [1] convert at /Users/sascha/.julia/v0.6/DynamicPolynomials/src/term.jl:23 [inlined]
 [2] Type at ./sysimg.jl:77 [inlined]
 [3] convert at /Users/sascha/.julia/v0.6/DynamicPolynomials/src/term.jl:24 [inlined]
 [4] setindex! at ./array.jl:583 [inlined]
 [5] copy!(::IndexLinear, ::Array{DynamicPolynomials.Term{true,Any},1}, ::IndexLinear, ::Array{DynamicPolynomials.PolyVar{true},1}) at ./abstractarray.jl:656
 [6] _subsmap(::MultivariatePolynomials.Subs, ::Array{DynamicPolynomials.PolyVar{true},1}, ::Tuple{Pair{DynamicPolynomials.PolyVar{true},Nemo.acb_poly}}) at /Users/sascha/.julia/v0.6/DynamicPolynomials/src/subs.jl:40
 [7] subs(::DynamicPolynomials.Polynomial{true,Int64}, ::Pair{DynamicPolynomials.PolyVar{true},Nemo.acb_poly}, ::Vararg{Pair{DynamicPolynomials.PolyVar{true},Nemo.acb_poly},N} where N) at /Users/sascha/.julia/v0.6/MultivariatePolynomials/src/substitution.jl:109
```

**Comment by PB12345** [comment]
I guess people would prefer to have Laplace expansion anyway. Do you think it's worth to implement it (although the computational complexity is bad...)?

**Comment by saschatimme** [comment]
I think Laplace expansion would be good to have. In the long term the way to go would be to have a [Smith normal form](https://en.wikipedia.org/wiki/Smith_normal_form) implementation

**Comment by PBrdng** [comment]
Hi,

the current implementation of `det` seems to be very slow for larger matrices. I have the following example:

```julia
using MultivariatePolynomials, DynamicPolynomials
@polyvar x[1:3] 
Ms = [randn(5,5) for i in 1:4]
Ms = map(M -> M + transpose(M), Ms)
M = sum(x[i] .* Ms[i] for i in 1:3) + Ms[4]
det(M)
```

which does not terminate after 5 minutes. By contrast, simple Laplace expansion is immediate. Can you confirm? And if yes, would it be a better idea to simply switch to Laplace expansion for `det()`?

**Comment by blegat** [comment]
Indeed, it is very slow ^^ Maybe automatically simplifying rational expression with `gcd` would make it faster

**Comment by PBrdng** [comment]
Could you try? Or otherwise I could write an implementation of the Laplace expansion.

I work with determinants quite often, so for me it would be important to be able to compute determinants until say 10x10.

**Comment by blegat** [comment]
I have implemented the `gcd` algorithm using the Euclidean algorithm which works for univariate polynomials. What is the recommended algorithm for computing the GCD of multivariate polynomials ?

**Comment by PBrdng** [comment]
> I have implemented the gcd algorithm using the Euclidean algorithm which works for univariate polynomials. What is the recommended algorithm for computing the GCD of multivariate polynomials ?

This I don't know, unfortunately :(

**Comment by saschatimme** [comment]
This question is tougher than one might think. I think most of the literature is about the symbolic case about some nice field like Q or Q[i]. There one general strategy is to reduce the problem first to the univariate case then factor this polynomial and recover the original polynomial by a technique called Hensel Lifting. The problem is that this is quite involved and heavily symbolic. If found one [reference](http://www.mmrc.iss.ac.cn/~lzhi/Publications/znascm00.pdf) where they extended such an algorithm to floating point arithmetic, but I have the feeling that this all quite an endeavour.

**Comment by PBrdng** [comment]
Hi,

since the determinant is not working in a satisfying way, I coded a simple Laplace expansion but that still runs faster than the default algorithm on DynamicPolynomials. Feel free to use it, if you want :)

```Julia
function Base.det(M::Matrix{<:MultivariatePolynomials.AbstractPolynomialLike}) 
    m = size(M)[1]
    if m > 2
        return sum((-1)^(i-1) * M[i,1] *  Det(M[1:end .!= i, 2:end]) for i in 1:m)
    else
        return M[1,1] * M[2,2] - M[2,1] * M[1,2]
    end
end
```

**Comment by blegat** [comment]
@PBrdng I would consider a PR adding this method in this package :) It should be faster that the current fallback on lufact
