### ISSUE TITLE
Zenodo

### ISSUE THREAD

**Issue by blegat** [JuliaAlgebra/MultivariatePolynomials.jl#74]
Any objection to use Zenodo to generate DOI's from versions of this package ? Zenodo will take care of creating a DOI automatically every time we create a release on Github just like attobot do with METADATA
cc @joehuchette @rdeits @saschatimme

**Comment by saschatimme** [comment]
sure why not

**Comment by rdeits** [comment]
Sure, sounds good to me

**Comment by joehuchette** [comment]
Nope
